cmake_minimum_required(VERSION 3.10)
project(AllLabs)

# Установка общего стандарта для C и C++
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Добавление всех лабораторных
add_subdirectory(Lab_type_№1)
add_subdirectory(Lab_Type_№2)
add_subdirectory(Lab_Type_№3)
add_subdirectory(Lab_Type_№4)
add_subdirectory(Lab_Type_№5)
add_subdirectory(Lab_Type_№6)
add_subdirectory(Lab_Type_№7)
add_subdirectory(Lab_Type_№8)
add_subdirectory(Lab_Type_№9)
add_subdirectory(Lab_Type_№10)
#add_subdirectory(Lab_Type_№11)
#add_subdirectory(Lab_Type_№12_Chapter_1)
