# Используем официальный минимальный образ Ubuntu
FROM ubuntu:22.04

# Установка зависимостей: компиляторы, cmake
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    && apt-get clean

# Рабочая директория в контейнере
WORKDIR /project

# Копируем весь проект в контейнер
COPY . .

# Создаем build-папку и собираем проект
RUN mkdir -p build && cd build && cmake .. && cmake --build .

# По умолчанию запускаем bash (можно заменить)
CMD ["/bin/bash"]
